INSERT INTO istudy.book (name, testament, category)
    VALUES ('Genesis', 'Old', 'Pentateuch'),
           ('Exodus', 'Old', 'Pentateuch'),
           ('Leviticus', 'Old', 'Pentateuch'),
           ('Numbers', 'Old', 'Pentateuch'),
           ('Deuteronomy', 'Old', 'Pentateuch'),
           ('Joshua', 'Old', 'Historical'),
           ('Judges', 'Old', 'Historical'),
           ('Ruth', 'Old', 'Historical'),
           ('1 Samuel', 'Old', 'Historical'),
           ('2 Samuel', 'Old', 'Historical'),
           ('1 Kings', 'Old', 'Historical'),
           ('2 Kings', 'Old', 'Historical'),
           ('1 Chronicles', 'Old', 'Historical'),
           ('2 Chronicles', 'Old', 'Historical'),
           ('Ezra', 'Old', 'Historical'),
           ('Nehemiah', 'Old', 'Historical'),
           ('Esther', 'Old', 'Historical'),
           ('Job', 'Old', 'Wisdom'),
           ('Psalms', 'Old', 'Wisdom'),
           ('Proverbs', 'Old', 'Wisdom'),
           ('Ecclesiastes', 'Old', 'Wisdom'),
           ('Song of Solomon', 'Old', 'Wisdom'),
           ('Isaiah', 'Old', 'Prophetic'),
           ('Jeremiah', 'Old', 'Prophetic'),
           ('Lamentations', 'Old', 'Prophetic'),
           ('Ezekiel', 'Old', 'Prophetic'),
           ('Daniel', 'Old', 'Prophetic'),
           ('Hosea', 'Old', 'Prophetic'),
           ('Joel', 'Old', 'Prophetic'),
           ('Amos', 'Old', 'Prophetic'),
           ('Obadiah', 'Old', 'Prophetic'),
           ('Jonah', 'Old', 'Prophetic'),
           ('Micah', 'Old', 'Prophetic'),
           ('Nahum', 'Old', 'Prophetic'),
           ('Habakkuk', 'Old', 'Prophetic'),
           ('Zephaniah', 'Old', 'Prophetic'),
           ('Haggai', 'Old', 'Prophetic'),
           ('Zechariah', 'Old', 'Prophetic'),
           ('Malachi', 'Old', 'Prophetic'),
           ('Matthew', 'New', 'Gospel'),
           ('Mark', 'New', 'Gospel'),
           ('Luke', 'New', 'Gospel'),
           ('John', 'New', 'Gospel'),
           ('Acts', 'New', 'Gospel'),
           ('Romans', 'New', 'Epistle'),
           ('1 Corinthians', 'New', 'Epistle'),
           ('2 Corinthians', 'New', 'Epistle'),
           ('Galatians', 'New', 'Epistle'),
           ('Ephesians', 'New', 'Epistle'),
           ('Philippians', 'New', 'Epistle'),
           ('Colossians', 'New', 'Epistle'),
           ('1 Thessalonians', 'New', 'Epistle'),
           ('2 Thessalonians', 'New', 'Epistle'),
           ('1 Timothy', 'New', 'Epistle'),
           ('2 Timothy', 'New', 'Epistle'),
           ('Titus', 'New', 'Epistle'),
           ('Philemon', 'New', 'Epistle'),
           ('Hebrews', 'New', 'Epistle'),
           ('James', 'New', 'Epistle'),
           ('1 Peter', 'New', 'Epistle'),
           ('2 Peter', 'New', 'Epistle'),
           ('1 John', 'New', 'Epistle'),
           ('2 John', 'New', 'Epistle'),
           ('3 John', 'New', 'Epistle'),
           ('Jude', 'New', 'Epistle'),
           ('Revelation', 'New', 'Epistle');
